/*
 Copyright 2005-2006 Seth Fitzsimmons <seth@mojodna.net>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
package net.mojodna.searchable;

/**
 * Barebones searcher interface.  Extend this if you wish to provide more
 * search methods in a generic manner.
 * 
 * @author Seth Fitzsimmons
 * @param <E> Type of object this is a Searcher for.
 */
public interface Searcher<E extends Result> {
	/**
	 * Searches the index.
	 * 
	 * @param query Query to use.
	 * @return ResultSet generated by the specified query
	 * @throws IndexException
	 */
	ResultSet<E> search(String query) throws IndexException;
    
    /**
     * Searches the index.
     * 
     * @param query Query to use.
     * @param start First result to return (paging).
     * @param count Number of results to return.
     * @return ResultSet for the specified query.
     * @throws IndexException
     */
    ResultSet<E> search(String query, Integer start, Integer count) throws IndexException;
}
